# Auto generated, do not edit.

PRODUCT_COPY_FILES += \
    prebuilts/calyx/fdroid/fallback-icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/fallback-icon.png \
    prebuilts/calyx/fdroid/repo/app.organicmaps/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/app.organicmaps/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/at.bitfire.davdroid/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/at.bitfire.davdroid/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/com.artifex.mupdf.viewer.app/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/com.artifex.mupdf.viewer.app/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/com.aurora.store/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/com.aurora.store/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/com.fsck.k9/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/com.fsck.k9/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/com.jarsilio.android.scrambledeggsif/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/com.jarsilio.android.scrambledeggsif/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/com.nextcloud.client/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/com.nextcloud.client/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/diff/1732248091000.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/diff/1732248091000.json \
    prebuilts/calyx/fdroid/repo/diff/1732334496000.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/diff/1732334496000.json \
    prebuilts/calyx/fdroid/repo/diff/1732420902000.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/diff/1732420902000.json \
    prebuilts/calyx/fdroid/repo/diff/1732507313000.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/diff/1732507313000.json \
    prebuilts/calyx/fdroid/repo/diff/1732593686000.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/diff/1732593686000.json \
    prebuilts/calyx/fdroid/repo/diff/1732680097000.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/diff/1732680097000.json \
    prebuilts/calyx/fdroid/repo/diff/1732766497000.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/diff/1732766497000.json \
    prebuilts/calyx/fdroid/repo/diff/1732939295000.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/diff/1732939295000.json \
    prebuilts/calyx/fdroid/repo/diff/1733025702000.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/diff/1733025702000.json \
    prebuilts/calyx/fdroid/repo/diff/1733112086000.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/diff/1733112086000.json \
    prebuilts/calyx/fdroid/repo/entry.jar:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/entry.jar \
    prebuilts/calyx/fdroid/repo/entry.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/entry.json \
    prebuilts/calyx/fdroid/repo/icons/fdroid-icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons/fdroid-icon.png \
    prebuilts/calyx/fdroid/repo/index.css:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/index.css \
    prebuilts/calyx/fdroid/repo/index.html:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/index.html \
    prebuilts/calyx/fdroid/repo/index.jar:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/index.jar \
    prebuilts/calyx/fdroid/repo/index.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/index.png \
    prebuilts/calyx/fdroid/repo/index-v1.jar:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/index-v1.jar \
    prebuilts/calyx/fdroid/repo/index-v1.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/index-v1.json \
    prebuilts/calyx/fdroid/repo/index-v2.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/index-v2.json \
    prebuilts/calyx/fdroid/repo/index.xml:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/index.xml \
    prebuilts/calyx/fdroid/repo/org.breezyweather/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.breezyweather/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/org.breezyweather/fr/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.breezyweather/fr/icon.png \
    prebuilts/calyx/fdroid/repo/org.breezyweather/it/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.breezyweather/it/icon.png \
    prebuilts/calyx/fdroid/repo/org.briarproject.briar.android/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.briarproject.briar.android/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/org.calyxinstitute.vpn/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.calyxinstitute.vpn/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/org.fdroid.basic/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.fdroid.basic/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/org.fdroid.fdroid/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.fdroid.fdroid/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/org.onionshare.android.fdroid/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.onionshare.android.fdroid/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/org.openobservatory.ooniprobe/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.openobservatory.ooniprobe/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/org.thoughtcrime.securesms/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.thoughtcrime.securesms/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/org.torproject.android/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.torproject.android/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/org.torproject.torbrowser/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.torproject.torbrowser/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/se.leap.riseupvpn/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/se.leap.riseupvpn/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/status/running.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/status/running.json \
    prebuilts/calyx/fdroid/repo/status/update.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/status/update.json \
    prebuilts/calyx/fdroid/repo/us.spotco.malwarescanner/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/us.spotco.malwarescanner/en-US/icon.png \

PRODUCT_PACKAGES += \
    fdroid-repo \
    fdroid-debug-repo \
    fdroid-basic-repo \
    fdroid-basic-debug-repo \
    aurora-store \
    AuroraStore \
    BreezyWeather \
    Briar \
    CalyxVPN \
    DAVx5 \
    F-Droid \
    F-DroidBasic \
    GCamPhotosPreview \
    Hypatia \
    K-9Mail \
    MuPDFviewer \
    Nextcloud \
    OnionShare \
    OONIProbe \
    Orbot \
    OrganicMaps \
    RiseupVPN \
    ScrambledExif \
    Signal \
    TorBrowser \
