# Auto generated, do not edit.

PRODUCT_COPY_FILES += \
    prebuilts/calyx/fdroid/fallback-icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/fallback-icon.png \
    prebuilts/calyx/fdroid/repo/app.organicmaps/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/app.organicmaps/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/at.bitfire.davdroid/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/at.bitfire.davdroid/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/com.artifex.mupdf.viewer.app/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/com.artifex.mupdf.viewer.app/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/com.aurora.store/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/com.aurora.store/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/com.fsck.k9/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/com.fsck.k9/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/com.jarsilio.android.scrambledeggsif/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/com.jarsilio.android.scrambledeggsif/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/com.nextcloud.client/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/com.nextcloud.client/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/diff/1727755310000.json:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/diff/1727755310000.json \
    prebuilts/calyx/fdroid/repo/diff/1727841716000.json:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/diff/1727841716000.json \
    prebuilts/calyx/fdroid/repo/diff/1727928091000.json:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/diff/1727928091000.json \
    prebuilts/calyx/fdroid/repo/diff/1728014489000.json:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/diff/1728014489000.json \
    prebuilts/calyx/fdroid/repo/diff/1728100896000.json:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/diff/1728100896000.json \
    prebuilts/calyx/fdroid/repo/diff/1728187342000.json:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/diff/1728187342000.json \
    prebuilts/calyx/fdroid/repo/diff/1728273697000.json:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/diff/1728273697000.json \
    prebuilts/calyx/fdroid/repo/diff/1728360089000.json:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/diff/1728360089000.json \
    prebuilts/calyx/fdroid/repo/diff/1728446510000.json:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/diff/1728446510000.json \
    prebuilts/calyx/fdroid/repo/diff/1728532923000.json:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/diff/1728532923000.json \
    prebuilts/calyx/fdroid/repo/entry.jar:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/entry.jar \
    prebuilts/calyx/fdroid/repo/entry.json:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/entry.json \
    prebuilts/calyx/fdroid/repo/icons/fdroid-icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/icons/fdroid-icon.png \
    prebuilts/calyx/fdroid/repo/index-v1.jar:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/index-v1.jar \
    prebuilts/calyx/fdroid/repo/index-v1.json:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/index-v1.json \
    prebuilts/calyx/fdroid/repo/index-v2.json:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/index-v2.json \
    prebuilts/calyx/fdroid/repo/index.css:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/index.css \
    prebuilts/calyx/fdroid/repo/index.html:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/index.html \
    prebuilts/calyx/fdroid/repo/index.jar:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/index.jar \
    prebuilts/calyx/fdroid/repo/index.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/index.png \
    prebuilts/calyx/fdroid/repo/index.xml:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/index.xml \
    prebuilts/calyx/fdroid/repo/org.breezyweather/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/org.breezyweather/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/org.breezyweather/fr/icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/org.breezyweather/fr/icon.png \
    prebuilts/calyx/fdroid/repo/org.breezyweather/it/icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/org.breezyweather/it/icon.png \
    prebuilts/calyx/fdroid/repo/org.briarproject.briar.android/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/org.briarproject.briar.android/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/org.calyxinstitute.vpn/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/org.calyxinstitute.vpn/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/org.fdroid.basic/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/org.fdroid.basic/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/org.onionshare.android.fdroid/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/org.onionshare.android.fdroid/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/org.openobservatory.ooniprobe/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/org.openobservatory.ooniprobe/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/org.thoughtcrime.securesms/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/org.thoughtcrime.securesms/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/org.torproject.android/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/org.torproject.android/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/org.torproject.torbrowser/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/org.torproject.torbrowser/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/se.leap.riseupvpn/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/se.leap.riseupvpn/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/status/running.json:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/status/running.json \
    prebuilts/calyx/fdroid/repo/status/update.json:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/status/update.json \
    prebuilts/calyx/fdroid/repo/us.spotco.malwarescanner/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/app/fdroid/repo/us.spotco.malwarescanner/en-US/icon.png \

PRODUCT_PACKAGES += \
    fdroid-repo \
    fdroid-debug-repo \
    fdroid-basic-repo \
    fdroid-basic-debug-repo \
    aurora-store \
    AuroraStore \
    BreezyWeather \
    Briar \
    CalyxVPN \
    DAVx5 \
    F-DroidBasic \
    GCamPhotosPreview \
    Hypatia \
    K-9Mail \
    MuPDFviewer \
    Nextcloud \
    OONIProbe \
    OnionShare \
    Orbot \
    OrganicMaps \
    RiseupVPN \
    ScrambledExif \
    Signal \
    TorBrowser \
